#
# CircleCI 2.0 Gatsby to Firebase Configuration File
#

version: 2
jobs:
  github-commit:
    docker:
      - image: circleci/node:10.10

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: npm install

      - run:
          name: Github Deploy
          command: node ./gatsby-node/updateGit.js

  build:
    docker:
      - image: circleci/node:10.10

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            # Find a cache corresponding to this specific package-lock.json checksum
            # when this file is changed, this key will fail
            - v1-npm-deps-{{ checksum "package-lock.json" }}
            # Find the most recently generated cache used from any branch
            - v1-npm-deps-

      - run:
          name: Install Dependencies
          command: npm install && node ./scripts/generate-markdown.js run

      - save_cache:
          key: v1-npm-deps-{{ checksum "package-lock.json" }}

          paths:
            - ./node_modules

      - run:
          name: Gatsby Build
          command: ./node_modules/.bin/gatsby build --prefix-paths

      - run:
          name: Copy Static
          command: node scripts/copy-static.js

      - run:
          name: Firebase Deploy
          command: ./node_modules/.bin/firebase deploy  --project dotnet-weekly --token=$FIREBASE_TOKEN

workflows:
  version: 2
  commit:
    jobs:
      - build
  nightly:
    triggers:
      - schedule:
          cron: '0 * * * *'
          filters:
            branches:
              only:
                - master
    jobs:
      - github-commit
